name: 'Test'

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'
  pull_request:
    branches:
      - 'main'

jobs:
  # unit runs the unit tests
  unit:
    strategy:
      fail-fast: false
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: |-
          make test

  # build runs go build on the target platforms to ensure the runtime links are
  # correct.
  build:
    strategy:
      fail-fast: false
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ "386", amd64, arm64 ]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows

    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-go@v5'
        with:
          go-version-file: 'go.mod'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |-
          make build